[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bitdeck"
authors = [{name = "bitdeck", email = "justinleebitdeckai@gmail.com"}]
dynamic = ["version", "v0.0.2"]
